create table if not exists public.weather_measurements (
    id bigint generated by default as identity primary key,
    station_id text not null,
    timestamp timestamptz not null,
    temperature numeric,
    wind_speed numeric,
    wind_gust numeric,
    wind_direction numeric,
    created_at timestamptz not null default now(),
    unique (station_id, timestamp)
);

create index if not exists weather_measurements_station_timestamp_idx
    on public.weather_measurements (station_id, timestamp desc);

alter table public.weather_measurements enable row level security;
